apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-02-18T12:43:49Z"
  generation: 1
  labels:
    app: talkiewalkie-back
  name: talkiewalkie-back
  namespace: default
  resourceVersion: "318768"
  selfLink: /apis/apps/v1/namespaces/default/deployments/talkiewalkie-back
  uid: 66c3afa4-378c-4b35-b533-272b11731c8d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: talkiewalkie-back
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: talkiewalkie-back
    spec:
      containers:
      - image: gcr.io/talkiewalkie-305117/talkiewalkie-back:0
        imagePullPolicy: IfNotPresent
        name: talkiewalkie-back
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-02-18T12:43:53Z"
    lastUpdateTime: "2021-02-18T12:43:53Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-02-18T12:43:49Z"
    lastUpdateTime: "2021-02-18T12:43:53Z"
    message: ReplicaSet "talkiewalkie-back-7fb97ff65" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
