apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: gcr.io/talkiewalkie-305117/webapp:852b7cc3d04c98eb92e69a1ebbe02b49301075db
        imagePullPolicy: Always
        name: webapp
        ports:
          - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
    - port: 80