apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: back
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:

      volumes:
        - name: google-cloud-key
          secret:
            secretName: backend-service-account

      containers:
        - image: gcr.io/talkiewalkie-305117/talkiewalkie-back:187e73796b5897c443d06a58a8b2b5f915fb2cf7
          imagePullPolicy: Always
          name: back
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8081
              name: health
          volumeMounts:
            - name: google-cloud-key
              mountPath: /var/secrets/google
          readinessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:8080" ]
            timeoutSeconds: 5
            periodSeconds: 30
            failureThreshold: 2
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pg_password
                  name: mysecrets
            - name: POSTGRES_HOST
              value: "pgsql"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/google/key.json"
            - name: POSTGRES_USER
              value: "postgres"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: jwt_secret
                  name: mysecrets
            - name: BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  key: bucket_name
                  name: mysecrets

      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: back
  annotations:
    cloud.google.com/app-protocols: '{"main":"HTTP2"}'
spec:
  type: ClusterIP
  selector:
    app: back
  ports:
    - port: 8080
      name: main
    - port: 8081
      name: health
