output = "models"

[psql]
dbname = "talkiewalkie"
host = "localhost"
port = 5432
user = "theo"
pass = ""
schema = "public"
sslmode = "disable"
add-global-variants	= false
wipe = true

[[types]]
  [types.match]
    name = "uuid"
  [types.replace]
    type = "uuid.UUID"
  [types.imports]
    third_party = ['"github.com/satori/go.uuid"']

#[[types]]
#  [types.match]
#    name = "start_point"
#  [types.replace]
#    type = "postgis.PointS"
#  [types.imports]
#    third_party = ['"github.com/cridenour/go-postgis"']
#
#[[types]]
#  [types.match]
#    name = "end_point"
#  [types.replace]
#    type = "postgis.PointS"
#  [types.imports]
#    third_party = ['"github.com/cridenour/go-postgis"']

