# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import audio_proc_pb2 as audio__proc__pb2


class CompressionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FormatAndCompress = channel.unary_unary(
                '/audioproc.Compression/FormatAndCompress',
                request_serializer=audio__proc__pb2.FormatAndCompressInput.SerializeToString,
                response_deserializer=audio__proc__pb2.FormatAndCompressOutput.FromString,
                )


class CompressionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FormatAndCompress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompressionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FormatAndCompress': grpc.unary_unary_rpc_method_handler(
                    servicer.FormatAndCompress,
                    request_deserializer=audio__proc__pb2.FormatAndCompressInput.FromString,
                    response_serializer=audio__proc__pb2.FormatAndCompressOutput.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audioproc.Compression', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Compression(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FormatAndCompress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/audioproc.Compression/FormatAndCompress',
            audio__proc__pb2.FormatAndCompressInput.SerializeToString,
            audio__proc__pb2.FormatAndCompressOutput.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
