// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package entities

import "errors"

type MessageCacheByInt struct {
	cache   map[int]*Message
	fetcher func([]int) ([]*Message, error)
	primer  func(value *Message) int
}

func NewMessageCacheByInt(
	fetcher func([]int) ([]*Message, error),
	primer func(value *Message) int,
) MessageCacheByInt {
	return MessageCacheByInt{
		cache:   map[int]*Message{},
		fetcher: fetcher,
		primer:  primer,
	}
}

func (cache *MessageCacheByInt) Get(
	identifiers []int,
) ([]*Message, error) {
	out := make([]*Message, len(identifiers))
	key2index := map[int]int{}

	for idx, key := range identifiers {
		item, ok := cache.cache[key]
		if ok {
			out[idx] = item
		} else {
			key2index[key] = idx
		}
	}

	if len(key2index) > 0 {
		missingKeys := make([]int, len(key2index))
		for key, _ := range key2index {
			missingKeys = append(missingKeys, key)
		}

		records, err := cache.fetcher(missingKeys)
		if err != nil {
			return nil, err
		}

		for idx := range records {
			key := missingKeys[idx]
			record := records[idx]

			out[key2index[key]] = record
			cache.cache[key] = record
		}
	}

	for _, value := range out {
		if value == nil {
			return nil, errors.New("could not fetch from : found nil value")
		}
	}

	return out, nil
}

func (cache MessageCacheByInt) Clear() {
	cache.cache = nil
}

func (cache MessageCacheByInt) Prime(values ...*Message) {
	for _, value := range values {
		cache.cache[cache.primer(value)] = value
	}
}

// ENSURE IMPORTS
var _ uuid2.UUID

type MessageCacheByUuid2UUID struct {
	cache   map[uuid2.UUID]*Message
	fetcher func([]uuid2.UUID) ([]*Message, error)
	primer  func(value *Message) uuid2.UUID
}

func NewMessageCacheByUuid2UUID(
	fetcher func([]uuid2.UUID) ([]*Message, error),
	primer func(value *Message) uuid2.UUID,
) MessageCacheByUuid2UUID {
	return MessageCacheByUuid2UUID{
		cache:   map[uuid2.UUID]*Message{},
		fetcher: fetcher,
		primer:  primer,
	}
}

func (cache *MessageCacheByUuid2UUID) Get(
	identifiers []uuid2.UUID,
) ([]*Message, error) {
	out := make([]*Message, len(identifiers))
	key2index := map[uuid2.UUID]int{}

	for idx, key := range identifiers {
		item, ok := cache.cache[key]
		if ok {
			out[idx] = item
		} else {
			key2index[key] = idx
		}
	}

	if len(key2index) > 0 {
		missingKeys := make([]uuid2.UUID, len(key2index))
		for key, _ := range key2index {
			missingKeys = append(missingKeys, key)
		}

		records, err := cache.fetcher(missingKeys)
		if err != nil {
			return nil, err
		}

		for idx := range records {
			key := missingKeys[idx]
			record := records[idx]

			out[key2index[key]] = record
			cache.cache[key] = record
		}
	}

	for _, value := range out {
		if value == nil {
			return nil, errors.New("could not fetch from : found nil value")
		}
	}

	return out, nil
}

func (cache MessageCacheByUuid2UUID) Clear() {
	cache.cache = nil
}

func (cache MessageCacheByUuid2UUID) Prime(values ...*Message) {
	for _, value := range values {
		cache.cache[cache.primer(value)] = value
	}
}

// ENSURE IMPORTS
var _ uuid2.UUID
