// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package entities

type UserSlice []User
type UserSlicePtrs []*User

func (slice UserSlice) UniqueBy(keyer func(User) interface{}) UserSlice {
	u := map[interface{}]User{}

	for _, item := range slice {
		key := keyer(item)
		u[key] = item
	}

	out := []User{}
	for _, item := range u {
		out = append(out, item)
	}
	return out
}

func (slice UserSlice) FilterBy(predicate func(User) bool) UserSlice {
	out := []User{}
	for _, item := range slice {
		if predicate(item) {
			out = append(out, item)
		}
	}

	return out
}

func (slice UserSlice) Contains(t User) bool {
	for _, item := range slice {
		if item == t {
			return true
		}
	}

	return false
}

func (slice UserSlice) IsEmpty() bool {
	return len(slice) == 0
}

// from https://stackoverflow.com/a/36000696
func (slice UserSlice) SameAs(other UserSlice) bool {
	if len(slice) != len(other) {
		return false
	}
	// create a map of string -> int
	diff := make(map[User]int, len(slice))
	for _, _x := range slice {
		// 0 value for int is 0, so just increment a counter for the string
		diff[_x]++
	}

	for _, _y := range other {
		// If the string _y is not in diff bail out early
		if _, ok := diff[_y]; !ok {
			return false
		}
		diff[_y] -= 1
		if diff[_y] == 0 {
			delete(diff, _y)
		}
	}

	return len(diff) == 0
}

//
// Slice of pointers
//

func (slice UserSlicePtrs) UniqueBy(keyer func(*User) interface{}) UserSlicePtrs {
	u := map[interface{}]*User{}

	for _, item := range slice {
		key := keyer(item)
		u[key] = item
	}

	out := []*User{}
	for _, item := range u {
		out = append(out, item)
	}
	return out
}

func (slice UserSlicePtrs) FilterBy(predicate func(*User) bool) UserSlicePtrs {
	out := []*User{}
	for _, item := range slice {
		if predicate(item) {
			out = append(out, item)
		}
	}

	return out
}

func (slice UserSlicePtrs) Contains(t *User) bool {
	for _, item := range slice {
		if item == t {
			return true
		}
	}

	return false
}

func (slice UserSlicePtrs) FilterNotNil() UserSlicePtrs {
	return slice.FilterBy(func(t *User) bool {
		return t != nil
	})
}

func (slice UserSlicePtrs) IsEmpty() bool {
	return len(slice) == 0
}

// from https://stackoverflow.com/a/36000696
func (slice UserSlicePtrs) SameAs(other UserSlicePtrs) bool {
	if len(slice) != len(other) {
		return false
	}
	// create a map of string -> int
	diff := make(map[User]int, len(slice))
	for _, _x := range slice {
		// 0 value for int is 0, so just increment a counter for the string
		diff[_x]++
	}

	for _, _y := range other {
		// If the string _y is not in diff bail out early
		if _, ok := diff[_y]; !ok {
			return false
		}
		diff[_y] -= 1
		if diff[_y] == 0 {
			delete(diff, _y)
		}
	}

	return len(diff) == 0
}
