# REF: https://docs.github.com/en/actions/guides/deploying-to-google-kubernetes-engine
name: GKE CI/CD

on:
  push:
    branches:
      - master

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: europe-west1-b
  GKE_CLUSTER: talkiewalkie-main
  IMAGE: talkiewalkie-back
  REGISTRY_HOSTNAME: gcr.io
  DEPLOYMENT_NAME: talkiewalkie-back

jobs:
  setup-build-publish-deploy:
    name: Backend test & deployment
    runs-on: ubuntu-latest

    services:
      test-db:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: theo
          POSTGRES_PORT: 5432
          POSTGRES_DB: talkiewalkie-test
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '336.0.0'
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_SA_B64 }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      - name: Test deps
        run: |
          # GO INSTALLL
          curl -LO https://golang.org/dl/go1.16.3.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.16.3.linux-amd64.tar.gz
          export PATH=$PATH:/usr/local/go/bin

      - name: Test
        run: |
          go test ./repository

      # Build the Docker image
      - name: Build
        run: |
          ./build_back.sh

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:$GITHUB_SHA

      # Set up kustomize
#      - name: Set up Kustomize
#        run: |
#          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
#          chmod u+x ./kustomize

      # Deploy the Docker image to the GKE cluster
#      - name: Deploy
#        run: |
#          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
#          ./kustomize edit set image $REGISTRY_HOSTNAME/$GKE_PROJECT/$IMAGE:${GITHUB_SHA}
#          ./kustomize build . | kubectl apply -f -
#          kubectl rollout status deployment/$DEPLOYMENT_NAME
#          kubectl get services -o wide